FROM  python:3.10.4

WORKDIR /app

RUN adduser python \
    && chown python:python -R /app

USER python 

COPY requirements.txt ./

RUN pip install -r requirements.txt \
    && pip install gunicorn

COPY *.py ./

ENV FLASK_DEBUG="false" \
    FLASK_APP="wsgi.py" \
    USER="python" \
    PATH="${PATH}:/home/python/.local/bin" \
    DUMMY_PNG_URL="http://localhost:3000"

EXPOSE 5000

CMD ["gunicorn","-b", "0.0.0.0:5000","wsgi:app"]